[DATASET]
originalTrainPathDataset=dataset/original/train
originalTestPathDataset=dataset/original/test
jsonTrainPathDataset=dataset/processed_jsons/train
jsonTestPathDataset=dataset/processed_jsons/test
graphTrainDatasetPath=dataset/graph/train
graphTestDatasetPath=dataset/graph/test
graphTestDatasetToShowPath=dataset/graph/test_to_show


[SETTINGS]
top_n_tf_idf_strings=100
tfidf_embedding_size=100
path_models=results/models
pathHyperopt=results/hyperopt
path_gnn_explainer_results=results/GNNExplainer
trainEpochs=2
hyperopt_max_eval=2
earlyStoppingThresh=10
test_batch_size=64
LSTM_sequence_length=8
prediction_type=soft
train_explainer_model=1
TestConfidenceResultsFileName=05-02-2025_21-16-10_TestConfidenceResults
top_n_subgraph_to_take=5
file_names_examples_to_explain=_1_graph14.pkl,_1_graph16.pkl,_2_graph4.pkl,_2_graph3.pkl
preprocess_json_dataset_pipeline=0
train_word2vec_model_pipeline=0
create_graph_dataset_pipeline=0
train_gnn_model_pipeline=0
optimize_gnn_model_pipeline=0
test_gnn_model_pipeline=0
explain_gnn_model_pipeline=0
isolate_graphs_to_explain_pipeline=1
generate_graphs_to_explain_pipeline=1